packages:
  - package
  - docs
  - examples/*

catalog:
  tsdown: ^0.18.0
  typescript: ^5.9.3

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
